CREATE TABLE "ContactContent" (
    "id" TEXT NOT NULL,
    "sectionKicker" TEXT NOT NULL DEFAULT 'Contacto',
    "sectionTitle" TEXT NOT NULL DEFAULT 'Estamos aqui para ti',
    "sectionDescription" TEXT NOT NULL DEFAULT 'Puedes contactarnos a traves de nuestras redes sociales, por correo electronico o visitar nuestro estudio fisico.',
    "instagramUrl" TEXT NOT NULL DEFAULT 'https://www.instagram.com/elizabeth.rizos',
    "instagramHandle" TEXT NOT NULL DEFAULT '@elizabeth.rizos',
    "tiktokUrl" TEXT NOT NULL DEFAULT 'https://www.tiktok.com/@elizabeth.rizos',
    "tiktokHandle" TEXT NOT NULL DEFAULT '@elizabeth.rizos',
    "facebookUrl" TEXT NOT NULL DEFAULT 'https://www.facebook.com/elizabethrizos',
    "facebookHandle" TEXT NOT NULL DEFAULT 'elizabeth rizos',
    "whatsappUrl" TEXT NOT NULL DEFAULT 'https://wa.me/34600000000',
    "whatsappLabel" TEXT NOT NULL DEFAULT 'Escribenos directamente',
    "emailPrimaryLabel" TEXT NOT NULL DEFAULT 'Consultas generales',
    "emailPrimary" TEXT NOT NULL DEFAULT 'hola@apoteosicas.com',
    "emailSecondaryLabel" TEXT NOT NULL DEFAULT 'Academia y cursos',
    "emailSecondary" TEXT NOT NULL DEFAULT 'academia@apoteosicas.com',
    "actionLabel" TEXT NOT NULL DEFAULT 'Reservar cita online',
    "actionHref" TEXT NOT NULL DEFAULT '/booking',
    "locationTitle" TEXT NOT NULL DEFAULT 'Nuestro Estudio',
    "address" TEXT NOT NULL DEFAULT E'Calle Ejemplo, 123\n28001 Madrid, Espana',
    "scheduleLine1" TEXT NOT NULL DEFAULT 'Lunes - Viernes: 10:00 - 20:00',
    "scheduleLine2" TEXT NOT NULL DEFAULT 'Sabado: 10:00 - 15:00',
    "scheduleLine3" TEXT NOT NULL DEFAULT 'Domingo: Cerrado',
    "mapsUrl" TEXT NOT NULL DEFAULT 'https://maps.google.com',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "ContactContent_pkey" PRIMARY KEY ("id")
);

INSERT INTO "ContactContent" (
  "id",
  "sectionKicker",
  "sectionTitle",
  "sectionDescription",
  "emailSecondaryLabel",
  "emailSecondary",
  "actionLabel",
  "actionHref",
  "locationTitle",
  "address",
  "scheduleLine1",
  "scheduleLine2",
  "scheduleLine3",
  "updatedAt"
)
VALUES
(
  'ACADEMIA',
  'Contacto academia',
  'Estamos aqui para acompanarte',
  'Escribenos por correo o WhatsApp para dudas sobre cursos, acceso, certificaciones y soporte de la plataforma.',
  'Soporte academia',
  'academia@apoteosicas.com',
  'Explorar cursos',
  '/courses',
  'Academia online',
  E'Academia digital.\nSoporte desde Palma de Mallorca.',
  'Lunes - Viernes: 09:00 - 18:00',
  'Sabado: soporte reducido',
  'Domingo: cerrado',
  NOW()
),
(
  'SALON',
  'Contacto salon',
  'Reserva y atencion personalizada',
  'Si quieres cita para el salon, escribenos por WhatsApp o reserva directo en Booksy.',
  'Reservas salon',
  'hola@apoteosicas.com',
  'Reservar en Booksy',
  'https://booksy.com/es-es/115013_apoteosicas-by-elizabeth-rizos-salon_peluqueria_69069_palma-de-mallorca',
  'Salon Apoteosicas',
  E'Carretera de Valldemossa, 33\n07010 Palma, Illes Balears',
  'Lunes - Viernes: 10:00 - 20:00',
  'Sabado: 10:00 - 15:00',
  'Domingo: cerrado',
  NOW()
);
